//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.ServiceReferencesum {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="WebApplication1", ConfigurationName="ServiceReferencesum.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="WebApplication1/data", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable data();
        
        [System.ServiceModel.OperationContractAttribute(Action="WebApplication1/data", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> dataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="WebApplication1/Sum", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Sum();
        
        [System.ServiceModel.OperationContractAttribute(Action="WebApplication1/Sum", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SumAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WebApplication1.ServiceReferencesum.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WebApplication1.ServiceReferencesum.WebService1Soap>, WebApplication1.ServiceReferencesum.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable data() {
            return base.Channel.data();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> dataAsync() {
            return base.Channel.dataAsync();
        }
        
        public string Sum() {
            return base.Channel.Sum();
        }
        
        public System.Threading.Tasks.Task<string> SumAsync() {
            return base.Channel.SumAsync();
        }
    }
}
